//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MenusServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menus", Namespace="http://www.jokeny.cn/")]
    [System.SerializableAttribute()]
    public partial class Menus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MNameField;
        
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Mid {
            get {
                return this.MidField;
            }
            set {
                if ((this.MidField.Equals(value) != true)) {
                    this.MidField = value;
                    this.RaisePropertyChanged("Mid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jokeny.cn/", ConfigurationName="MenusServiceReference.GetMenusSoap")]
    public interface GetMenusSoap {
        
        // CODEGEN: 命名空间 http://www.jokeny.cn/ 的元素名称 GetTopMenusesResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jokeny.cn/GetTopMenuses", ReplyAction="*")]
        Client.MenusServiceReference.GetTopMenusesResponse GetTopMenuses(Client.MenusServiceReference.GetTopMenusesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopMenusesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopMenuses", Namespace="http://www.jokeny.cn/", Order=0)]
        public Client.MenusServiceReference.GetTopMenusesRequestBody Body;
        
        public GetTopMenusesRequest() {
        }
        
        public GetTopMenusesRequest(Client.MenusServiceReference.GetTopMenusesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTopMenusesRequestBody {
        
        public GetTopMenusesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopMenusesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopMenusesResponse", Namespace="http://www.jokeny.cn/", Order=0)]
        public Client.MenusServiceReference.GetTopMenusesResponseBody Body;
        
        public GetTopMenusesResponse() {
        }
        
        public GetTopMenusesResponse(Client.MenusServiceReference.GetTopMenusesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.jokeny.cn/")]
    public partial class GetTopMenusesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.MenusServiceReference.Menus[] GetTopMenusesResult;
        
        public GetTopMenusesResponseBody() {
        }
        
        public GetTopMenusesResponseBody(Client.MenusServiceReference.Menus[] GetTopMenusesResult) {
            this.GetTopMenusesResult = GetTopMenusesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetMenusSoapChannel : Client.MenusServiceReference.GetMenusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenusSoapClient : System.ServiceModel.ClientBase<Client.MenusServiceReference.GetMenusSoap>, Client.MenusServiceReference.GetMenusSoap {
        
        public GetMenusSoapClient() {
        }
        
        public GetMenusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetMenusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMenusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMenusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.MenusServiceReference.GetTopMenusesResponse Client.MenusServiceReference.GetMenusSoap.GetTopMenuses(Client.MenusServiceReference.GetTopMenusesRequest request) {
            return base.Channel.GetTopMenuses(request);
        }
        
        public Client.MenusServiceReference.Menus[] GetTopMenuses() {
            Client.MenusServiceReference.GetTopMenusesRequest inValue = new Client.MenusServiceReference.GetTopMenusesRequest();
            inValue.Body = new Client.MenusServiceReference.GetTopMenusesRequestBody();
            Client.MenusServiceReference.GetTopMenusesResponse retVal = ((Client.MenusServiceReference.GetMenusSoap)(this)).GetTopMenuses(inValue);
            return retVal.Body.GetTopMenusesResult;
        }
    }
}
